### ISSUE TITLE
Seperate app name for console

### ISSUE THREAD

**Issue by spinx** [ekino/EkinoNewRelicBundle#102]
I'd like to split the CLI operations into a seperate NR app. I'd need an option to name the app differently if the app is ran as a console command.

Would you merge such PR?

**Comment by spinx** [comment]
@odolbeau @rande Thoughts?

**Comment by rande** [comment]
This can be done by setting a custom env and so a custom configuration file.

**Comment by spinx** [comment]
I don't agree custom Symfony environment is the right approach. People may have other systems in place that rely on the environment being 'production' so setting something else is not really a good idea. 

Use case:
Notify via pagerduty if error rate on production is more than 5% 

CLI is just an execution environment that runs in production, so we should get notified. Adding another environment just results in loads of problems down the line.

**Comment by rande** [comment]
if you run the production environment with long cli process php; this will lead to error as configuration should be quite different (I have monolog in mind and doctrine). For experience, we always run the cli env with dedicated settings.

**Comment by spinx** [comment]
That is true, I agree, still, we don't have that problem on quite a large scale, so for us this option is still very much needed.
