### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by Solution** [ekino/EkinoNewRelicBundle#104]
Hello,

we update our new relic bundle to last release(1.3.2) from 1.2.3, right after that our application avg page load increased about 75 percent, after downgrade it went immediately down(original values). 
Anyone has a experience with issue like that? 

![ekino](https://cloud.githubusercontent.com/assets/700211/12626169/9dc1eebe-c537-11e5-954c-8f5423bf2975.PNG)

**Comment by ibasaw** [comment]
+1

**Comment by ibasaw** [comment]
i resolved my issue but uninstall new relic php agent, re install it, reload all and problem is gone

**Comment by rande** [comment]
Sorry for the delay: here the code diff https://github.com/ekino/EkinoNewRelicBundle/compare/1.2.3...1.3.2 not sure there is something that can explain a x2 in performance drop.

**Comment by jderusse** [comment]
Did you investigate on the performance source?
You may use tools like blackfire to compare performance with 1.2 and 1.3

**Comment by pavelkucera** [comment]
Unfortunately, we were not able to find the source of the delay.

**Comment by pavelkucera** [comment]
Hi, we have completely changed the stack in the meantime, and thus we are not able to verify whether there has been any improvement.

Unless somebody else has run into a similar problem, I think that you can close this issue, as we are not able to provide more relevant information.
