### ISSUE TITLE
Allow modification of the Exception reported to New Relic

### ISSUE THREAD

**Issue by Lumbendil** [ekino/EkinoNewRelicBundle#107]
Atm we always send the Exception received, except when it's a 404. The issue with this is that, if there is a wrapper exception (for instance, twig) it reduces visibility of the actual issue.

I'd propose that a listener is called before calling the interactor, which would allow us to modify the exception being thrown.

I'm proposing a listener so the user is able to customize it in any way they want.

**Comment by jderusse** [comment]
what's about implementing your own ExcpetionListener for that purpose?

**Comment by Nyholm** [comment]
Using a custom `ExceptionListener` is how I would do it as well.
