### ISSUE TITLE
Enabling use_symfony_cache causes misreporting of http response codes

### ISSUE THREAD

**Issue by araines** [ekino/EkinoNewRelicBundle#120]
I've spent a considerable period of time tracking this down, and at this stage I'm not sure if its a problem with this bundle, or the new relic agent itself.

However, when I enable `use_symfony_cache` in the configuration (we do use it), the httpResponseCode we see in New Relic is always set to 200, even though we see 400s being served.

It seems to be related to calling `newrelic_end_transaction()` - if I stop this from being called then it reports correctly.

This may be related to #57.

**Comment by araines** [comment]
I've discussed this further with New Relic to get to the bottom of the behaviour.  Here is my diagnosis of the situation:

> When configured in a certain way, during the onCoreResponse event, it calls `newrelic_end_transaction`. This occurs here: 
> https://github.com/ekino/EkinoNewRelicBundle/blob/master/Listener/ResponseListener.php#L118
> 
> The onCoreResponse event is called with a priority of -255 during the Symfony `kernel.response` event:
> https://symfony.com/doc/current/components/http_kernel.html#creating-an-event-listener 
> https://symfony.com/doc/current/components/http_kernel.html#the-kernel-response-event
> 
> The priority means it should be the last listener to execute during the `kernel.response` event.
> 
> From my understanding of the Symfony event chain, I don't think at this stage the framework has actually started to stream the response back to the webserver. But I don't know enough about how the New Relic Agent works to say whether or not this is a problem - ultimately at this stage a Symfony Response object has been created and I believe will have the correct status code set in it.

Here is their response:

> The PHP agent gets the response code from the internal PHP SAPI state, and not from instrumenting any user generated code. Basically, when you call header() to set the response code, PHP sets a field in an internal struct used by the server API (ie PHP-FPM or the Apache module), and the PHP agent reads it back out of there at the end of the transaction.
> 
> In this struct, 200 is the default response code. So I believe that when you were calling newrelic_end_transaction, the response code in the struct had yet to be set, so it was returning the default of 200 for everything.

From this I believe this bundle is calling `newrelic_end_transaction()` too early which causes the incorrect reporting of the http status code for the response.  Instead the call should be made after the response code has actually been set by Symfony.


In order to work around this problem, I've simply disabled `use_symfony_cache` at the moment as I believe its behaviour is broken.

**Comment by rande** [comment]
@araines should the event changed from ``kernel.response`` to ``kernel.terminate`` in 
https://github.com/ekino/EkinoNewRelicBundle/blob/master/Resources/config/services.xml

**Comment by araines** [comment]
I _think_ so, as that would be triggered after the response has been sent.  However, I don't want to say that is the case with authority as I'm not 100% certain how the `use_symfony_cache` functionality was supposed to work and whether moving the event will break that.

**Comment by Nyholm** [comment]
Closing due inactivity. 

#eu-fossa
