### ISSUE TITLE
Bundle does not only report exceptions, no error reporting

### ISSUE THREAD

**Issue by klausbreyer** [ekino/EkinoNewRelicBundle#121]
Hi, 

I am using your bundle on Elastic Beanstalk. 

It works fine and everything. But it just seems to log exceptions. Is there any possibility to log errors as well? I mean errors like the ones I log with Monlog into the prod.log ?

![screen shot 2017-10-13 at 08 57 00](https://user-images.githubusercontent.com/32771/31533840-849734b8-aff4-11e7-92ea-4476e788b645.png)

I am just curious: Is this a problem of elastic beanstalk or is it something I can configure within this bundle?

**Comment by rande** [comment]
@klausbreyer As far as I remember, the new relic agent log exception not the bundle. Also new relic is not a log management system ...

**Comment by klausbreyer** [comment]
good point. thank you!
