### ISSUE TITLE
Bump new version

### ISSUE THREAD

**Issue by jaymecd** [ekino/EkinoNewRelicBundle#122]
Hi, are there any plans to bump a new version, as there are [number of changes](https://github.com/ekino/EkinoNewRelicBundle/compare/1.3.2...master) towards PHP 7.
appreciated

**Comment by DonCallisto** [comment]
Moreover I see that `master` has some commits  (15 at the time of writing) more than last tagged release. If no issues related, you should think to make a new release in order to avoid someone to stay with `dev-master` version (or similar)

**Comment by Nyholm** [comment]
1.4 was released i November. No changes has been merged since.
