### ISSUE TITLE
Can't turn off new relic without recompiling the container

### ISSUE THREAD

**Issue by iltar** [ekino/EkinoNewRelicBundle#127]
When you have the bundle active in an application and you turn new relic off, you get exceptions: 
`Attempted to call function "newrelic_name_transaction" from namespace "Ekino\Bundle\NewRelicBundle\NewRelic".`

I believe that all calls to actual new relic functions should be wrapped by a delegator that can check whether or not new relic is active when it's initialized.

**Comment by Nyholm** [comment]
True, how do you suggest one should fix this issue?

**Comment by iltar** [comment]
https://github.com/ekino/EkinoNewRelicBundle/blob/92877a9ba014401d635da4890ca0f5b2d9df1c59/DependencyInjection/EkinoNewRelicExtension.php#L46-L59

We can change the interactor to always be the reak one, but forward the calls to the blackhole by checking `extension_loaded('newrelic')` runtime instead of compile time.

**Comment by Nyholm** [comment]
Hm.. Sure.. 
Could you tell me about your use case? I do not really understand why you would like to add and remove PHP extensions without rebuilding your container.

**Comment by Nyholm** [comment]
Okey. Have a look at #134. It will allow you to specify `interactor: 'ekino.new_relic.interactor.auto'`. That interactor will check if the function exists before calling it. That would fix your scenario, right?

**Comment by iltar** [comment]
I think it would, but I have a small (performance) proposal which I will add to the PR
