### ISSUE TITLE
Moving forward

### ISSUE THREAD

**Issue by Nyholm** [ekino/EkinoNewRelicBundle#135]
Symfony 4 is out and we do not support it yet. @ChristianVermeulen opened PR #129 which removes Silex support and breaks BC. I added support for multiple interactors in #134 where I found out that this bundle is real old. =)

Last release was almost 6 months ago.
Question: Should we drop support for SF<3.4 and PHP <7.1?

It would not give us much more new features but this is a good place to remove all our legacy code.

**Comment by Tobion** [comment]
I think it's a good idea to drop sf < 3.4 support. PHP 7.1 requirement is fine for me. But I don't think the bundle gains much from 7.1 min requirement. So we could also support 7.0 for now IMO.

**Comment by magnusnordlander** [comment]
As long as we're upping the major version of the bundle when introducing a BC break, I'm pro dropping Symfony < 3.4. It's not like the current versions are not working, so if you're on 3.4 you can remain on a current version.

**Comment by Nyholm** [comment]
Thank you for the feedback!

**Comment by Nyholm** [comment]
The 2.0.0 version is soon ready to be released. Im going to close this now.
