### ISSUE TITLE
SonataBlockBunde and SonataAdminBundle integration

### ISSUE THREAD

**Issue by Nyholm** [ekino/EkinoNewRelicBundle#137]
I have very little knowledge of these bundles. Could someone give their opinion if we still need that integration. I see that we support version ^2.2 but 3.0 was released quite some time ago. 

Pinging @Soullivaneuh and @OskarStark. Does this integration make sense to have here?

**Comment by kunicmarko20** [comment]
@jordisala1991 @greg0ire I never used NewRelic but maybe you can help if it makes sense to still keep this?

**Comment by jordisala1991** [comment]
Added here: https://github.com/ekino/EkinoNewRelicBundle/pull/59

**Comment by greg0ire** [comment]
I think reasonable people are using 3, so this probably has very few users. It's sensible to remove the integration if no one asked for compatibility with 3.

**Comment by Nyholm** [comment]
Yeah. You are right. Thank you for the feedback.
