### ISSUE TITLE
Enable StyleCI

### ISSUE THREAD

**Issue by Nyholm** [ekino/EkinoNewRelicBundle#142]
That would be great with some forced code style

**Comment by Nyholm** [comment]
Btw, enabling ScrutinizerCI could also be a good idea.

**Comment by jderusse** [comment]
At the moment, the StyleLint is performed by travis through php-cs-fixer. There isn't any UI, just a green/red deployment status.

We can fix this by integrating a Style tools, but IMHO this tool should be compatible with the rules defined in php-cs-fixers (I don't like to define rules in 2 places). 

Did someone tries flintci.io ? (promoted by the maintener of https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge)

**Comment by jderusse** [comment]
What's about https://prettyci.com/?

**Comment by jderusse** [comment]
What do you mean by `sent a request`? the Open Source plan is free. We can configure it in this repo

**Comment by mnapoli** [comment]
Let me know if you have any issue setting it up, I'm ironing out the last bugs ^^

**Comment by Nyholm** [comment]
Thank you
