### ISSUE TITLE
Enabling native_function_invocation

### ISSUE THREAD

**Issue by jderusse** [ekino/EkinoNewRelicBundle#169]
Add leading \ before function invocation of internal function to speed up resolving.

Are you Pro or Con?

**Comment by Nyholm** [comment]
Oh. I’m not sure. Have barley seen any library do this. How much of performance increase will it be?
What is your opinion?

**Comment by jderusse** [comment]
This is not a big improvement (we are talking about 3% per call), but given the purpose of this bundle is to run on production, I think the question should be addressed.

As you, my eyes hurt when I open a project with such notation, (I think it could be a matter of habbit, and with time we can use to it) that's why I open this issue.

note that with php-cs-fixer, we've nothing to do...

**Comment by Nyholm** [comment]
3% per call is actually more than I thought. Let’s do it :)
