### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by redayoub** [ekino/EkinoNewRelicBundle#198]
I'm getting this error after upgrading to 2.0

`Type error: explode() expects parameter 2 to be string, null given in Configuration.php (line 42)
`

**Comment by Nyholm** [comment]
Thank you
Could you give me your configuration?

**Comment by redayoub** [comment]
symfony: 4.0.6,
ekino/newrelic-bundle: 2.0.0

do you need something else ?

**Comment by Nyholm** [comment]
That is what goes in your composer.json. 

I would like to see the config for the bundle. I would also like you to try the changes I made in #199.

**Comment by redayoub** [comment]
The fix in #199 worked, but I'm getting a new error

`The service "ekino.new_relic.exception_listener" has a dependency on a non-existent service "ekino.new_relic.interactor".`

**Comment by jderusse** [comment]
The Bundle don't use `ekino.new_relic.exception_listener` anymore (see https://github.com/ekino/EkinoNewRelicBundle/blob/master/UPGRADE-2.0.md) is it a custom service in your project?

Can you, please, try to clear cache?

**Comment by redayoub** [comment]
@jderusse it was that thanks.
