### ISSUE TITLE
Add APP_ID

### ISSUE THREAD

**Issue by redayoub** [ekino/EkinoNewRelicBundle#200]
I can't find where I can specify the APP_ID for new relic.

Also it seems that only deployment notifications are sent when I run "newrelic:notify-deployment", when a 500 or 404 error happens nothing is sent. I'm using the same config in the doc for the version 2.0.

**Comment by Nyholm** [comment]
APP_ID is just a name. You set it with `ekino_new_relic.application_name` in your config. 

Deployment notification tells new relic that you have deployed a new version. It is nothing you should send when you get a 500 error.

**Comment by redayoub** [comment]
I wanted to say that the only things that works are the deployment notifications. When I try to  generate manually a 404 or 500 error in symfony nothing is sent to newrelic.

**Comment by Nyholm** [comment]
404's should not be reported. See https://github.com/ekino/EkinoNewRelicBundle/blob/master/Listener/ExceptionListener.php#L44

Try write this in a controller action: 

```php
throw new \Exception('Test exception');
```

**Comment by Nyholm** [comment]
Also, do you have the newrelic extension installed?

**Comment by redayoub** [comment]
Throwing the exception doesn't send any new relic notifications.

What do you mean by the newrelic extension?

**Comment by Nyholm** [comment]
You need to install the NewRelic PHP extension to use NewRelic. See https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-overview

**Comment by Nyholm** [comment]
Did you manage to get it working?

**Comment by jderusse** [comment]
Closing the issue. @redayoub feel free to re-open with more informations
