### ISSUE TITLE
Explain interactors

### ISSUE THREAD

**Issue by paymonyau** [ekino/EkinoNewRelicBundle#201]
Hi, 

I'm having a difficult time setting this up. Could you explain interactors and give examples of YAML files.

If it requires the installation of anything extra. please explain that too. Everything I should need to know should be in the readme.ME. I shouldn't need to do research on this.

Thanks,

Paymon

**Comment by Nyholm** [comment]
Hey. 
You are absolutely correct. Could you explain what you do not understand? 

You can read more about interactors here: https://github.com/ekino/EkinoNewRelicBundle#interactor-services
Here is how you install it: https://github.com/ekino/EkinoNewRelicBundle#installation
Here is an exampled Yaml: https://github.com/ekino/EkinoNewRelicBundle#step-3--configure-the-bundle

**Comment by nnnikolay** [comment]
@paymonyau just use `auto` I think it should solve your question

**Comment by paymonyau** [comment]
It ended up being a legacy problem, one of the devs overrode a property on the old version and it was breaking the code. Falsely pointing to the interactors. After I removed the override, everything worked smoothly.

**Comment by jderusse** [comment]
Thank you @paymonyau for the feedback.
