### ISSUE TITLE
Require symfony to enable debug to work with the bundle

### ISSUE THREAD

**Issue by mmoreram** [ekino/EkinoNewRelicBundle#205]
I've been working for a while with this bundle, and after a lot of hours, I discovered that the kernel needs to be instanced with debug=true.

This may be trivial, but for example, Symfony Standard edition is distributed with debug=false in prod environment.

I've been searching for some resources, but didn't find any reason to think that I'm wrong.
Can anyone tell me I'm wrong?

Otherwise, I think that this should be added as a requirement in the configuration section of the documentation.

**Comment by jderusse** [comment]
Indeed, there is something weird in your issue. You shouldn't run a production environment with debug true.
Maybe you did not clear the cache on your production environment. Try to `rm -rf var/cache/*`

**Comment by Nyholm** [comment]
Yes. There is no such thing. 
What version are you running? What interactor are you using?

**Comment by mmoreram** [comment]
Well, I'm using the bundle inside a ReactPHP based application.
This is the configuration I create by using a compiler pass.
https://github.com/apisearch-io/search-server/blob/master/Plugin/NewRelic/DependencyInjection/NewRelicPluginExtension.php#L125

By enabling debug, it works properly.
Otherwise, I doesn't.

And thinking about it, it makes sense. I'm not using apache, nor nginx, not anything but a simple PHP thread, so consider my application like a php script that creates a Kernel. The only way that NewRelic can know about the server actions is by enabling debug.

Maybe is beacuse I don't understand that much how debug works inside the kernel, but how can NewRelic know about the transactions without debug?

**Comment by mmoreram** [comment]
Ok. Tested again in my home, and now, without any change, it properly works.
I see that there is a request listener that names the transaction.
Closing the issue :)
