### ISSUE TITLE
Using deprecated features - Symfony 4.1

### ISSUE THREAD

**Issue by khalil1608** [ekino/EkinoNewRelicBundle#220]
Ekino\NewRelicBundle\Exception\DeprecationException: Noticed exception 'Ekino\NewRelicBundle\Exception\DeprecationException' with message 'Checking for the AdvancedUserInterface in "Symfony\Component\Security\Core\Authentication\Token\AbstractToken::hasUserChanged()" is deprecated since Symfony 4.1 and support for it will be removed in 5.0. Implement the Symfony\Component\Security\Core\User\EquatableInterface to check if the user has been changed,' in /var/www/www-platform/shared/vendor/symfony/security/Core/Authentication/Token/AbstractToken.php:257 

Ekino\NewRelicBundle\Exception\DeprecationException: Noticed exception 'Ekino\NewRelicBundle\Exception\DeprecationException' with message 'Calling "Symfony\Component\Security\Core\User\UserChecker::checkPreAuth()" with an AdvancedUserInterface is deprecated since Symfony 4.1. Create a custom user checker if you wish to keep this functionality.' in /var/www/www-platform/shared/vendor/symfony/security/Core/User/UserChecker.php:36 

Ekino\NewRelicBundle\Exception\DeprecationException: Noticed exception 'Ekino\NewRelicBundle\Exception\DeprecationException' with message 'The "Sensio\Bundle\FrameworkExtraBundle\Configuration\Route" annotation is deprecated since version 5.2. Use "Symfony\Component\Routing\Annotation\Route" instead.' in /var/www/www-platform/shared/vendor/sensio/framework-extra-bundle/Configuration/Route.php:16

**Comment by jderusse** [comment]
Those are exceptions logged by the deprecation listener telling you that you (or one of your bundle) is using a deprecated method/class.

There is nothing related with `EkinoNewRelicBundle` and nothing we can do.

You should either:
- fix the deprecation (look at the stack trace to findout who triggered the error)
- desactivate the feature to no been warned when a depreacation error is triggered
```
ekino_new_relic:
    deprecations: false
```
