### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by brunoric** [ekino/EkinoNewRelicBundle#229]
Hi, 

Would be great if you release a 2.0.3 with the latest issues fixed. There are a couple of them that would be grand to have in a stable release. 

Do you need any help with that?

Thanks!
Bruno

**Comment by florianajir** [comment]
don't know if will fix it but since I upgraded newrelic-agent along with php 7.2.19, newrelic does not show anymore anything else than commands.

**Comment by Nyholm** [comment]
Thank you

I just released 2.1.0.

**Comment by brunoric** [comment]
Thanks!!
