### ISSUE TITLE
Traces after terminate event

### ISSUE THREAD

**Issue by ewgRa** [ekino/EkinoNewRelicBundle#233]
As far as I see bundle listen to KernelResponse event and end newrelic transaction there, that totally makes sense.

Is there any advice on how to trace everything that happens after the terminate event?
I see one way is to create a high priority listener that will listen Terminate event and will start new newrelic transaction and somewhere in shutdown will end it. Will it work?

Any better solution?

Thanks

**Comment by jderusse** [comment]
The `Kernel::Terminate` event is the latest hook point in the Request handle process.
IMHO, Everything that happends after that event is not related to the request, and should not reported in the "transaction". 
If you don't wan't to rely on Kernel Event, I suggest to add you custom new_relic_start/end call directly in `/public/index.php`

**Comment by ewgRa** [comment]
Thanks @jderusse for answering.
