### ISSUE TITLE
Using newrelic_set_appname discards metrics

### ISSUE THREAD

**Issue by magnusnordlander** [ekino/EkinoNewRelicBundle#24]
Upon reading the New Relic PHP API docs I stumbled upon the following:

> The xmit flag is new in version 3.1 of the agent. Usually, when you change an 
> application name, the agent simply discards the current transaction and does not 
> send any of the accumulated metrics to the daemon. However, if you want to record 
> the metric and transaction data up to the point at which you called this function, you 
> can specify a value of true for this argument to make the agent send the transaction 
> to the daemon. This has a very slight performance impact as it takes a few 
> milliseconds for the agent to dump its data. By default this parameter is false.

([source](https://newrelic.com/docs/php/the-php-api#api-set-appname))

If my reading is correct, because `newrelic_set_appname` is called relatively late we're discarding a bunch of useful metrics regarding framework performance, and bundle initialization performance.

Because we can now disable app naming, this is somewhat mitigated, but I consider this to be somewhat of a problem, and I think we should discuss possible solutions.

The way I see it (and interpret the docs) we have a few options:
1. Remove the ability to set the app name
2. Set the app name earlier (possibly in the bundle boot method?)
3. Use the xmit parameter
4. Document the behavior and do nothing about it

Now, options 1 and 4 comes with the obvious caveats. 

Option number 2 is of course problematic because the earliest point we can hook in that I can come up with is Bundle::boot(), but that is sketchy at best because we'd still have to encourage users to keep this bundle very high in the bundle order, and even then we're missing a potentially useful metrics.

If I interpret the docs correctly, option number 3 causes two transactions per request, one with the default app name, containing metrics up to the point where we call `newrelic_set_appname`, and one containing the data we collect today. Now, one could make the argument that collecting the data (even if the collection is flawed) is better than not collecting the data, but I'm not sure. Splitting transactions would make working with New Relic a worse experience.

What does everyone else think? I'm not at all sure, but I'm leaning towards option 1, because if we can't do it well, we shouldn't do it at all.

**Comment by fabian** [comment]
The `xmit` parameter has been introduced in #34 - I think this issue can be closed.

**Comment by mnapoli** [comment]
The `xmit` parameter is definitely the best solution, however I wonder too if it creates 2 transactions… I have asked New Relic's support for a clarification on the documentation. Until we get an answer I think this issue should stay open.

**Comment by mnapoli** [comment]
I got an answer from New Relic's support:

> XMIT = true will define that instead of dumping the metrics upon receiving a request to change appname, it will report existing data to the existing appname, and then dump that to our daemon for transport, **then start a fresh transaction, with fresh appname and report that separately.**

I've been advised to set the app name the earliest possible, which is unfortunately not really compatible with booting Symfony's container first. For our use case we'll fall back on using the extension's functions.

I agree that it should be documented, the ability to set the app name might even make sense to be removed? Thoughts?

**Comment by Nyholm** [comment]
Closing due inactivity. 

#eu-fossa
