### ISSUE TITLE
v1.1.* + Use BlackholeInteractor with LoggingInteractorDecorator without using newrelic extensions => don't log!

### ISSUE THREAD

**Issue by oversanne** [ekino/EkinoNewRelicBundle#56]
Hello,

In development environment, I didn't install newrelic extension and my project is based on Symfony 2.1, so I'm using v1.1.0 version of EkinoNewRelicBundle.

I'm using LoggingInteractorDecorator to check the good implementation of Newrelic on my environment and I'm using BlackholeInteractor (so it won't fail when calling newrelic methods).

But it doesn't work because EkinoNewRelicBundle disable its own listener here: https://github.com/ekino/EkinoNewRelicBundle/blob/1.1.0/DependencyInjection/Compiler/NewRelicCompilerPass.php#L33.

I would like to propose a fix on 1.1.0 branch, but you don't have a such branch 1.1. Could you create it or help me to find a solution to by-pass it?

Thanks for your help,

Olivier V.

**Comment by Nyholm** [comment]
Thank you for this issue. It is fixed in 1.4.0 (or earlier).
