### ISSUE TITLE
Notify deployment nodes

### ISSUE THREAD

**Issue by jaymecd** [ekino/EkinoNewRelicBundle#64]
Is it really required to notify NewRelic on each node in a cluster? 

I have around 20 nodes and see same number of events at NewRelic screen, what is a little bit annoyed and makes all charts pretty ugly.

It would be better to execute task once, on primary node, eg. `:roles => :app, :only => { :primary => true }`

**Comment by rande** [comment]
Seems to be the case now: https://github.com/ekino/EkinoNewRelicBundle/blob/master/Resources/recipes/newrelic.rb#L5
