### ISSUE TITLE
Use Application Name from php.ini if not set in config file

### ISSUE THREAD

**Issue by epicwhale** [ekino/EkinoNewRelicBundle#66]
In my opinion, it could be cleaner to maintain the license key, application name, etc in the PHP ini file instead of the symfony config file. (especially when having multiple nodes).

But I've noticed some parts of the Bundle will fail to function appropriately unless the 'name' property in the NewRelic class is set to something other than null. (for example the application name used during deployment).

Perhaps we should set the name of the application in the NewRelic class to the value from PHP ini if its not set in the symfony config file? We should still skip the setApplicationName(..) calls on the interactor, but not leave the application name empty in NewRelic.

Alternatively, we could just put a logic in the Deployment command where if the New Relic application name is not set, it should read it from the PHP ini file and use that instead?

What are your thoughts?

**Comment by rande** [comment]
This commit https://github.com/ekino/EkinoNewRelicBundle/commit/496f605eb02cda171393c1d80a154b85fd7cfc39 fix the issue.
