### ISSUE TITLE
Does not listen to Console Commands Exceptions?

### ISSUE THREAD

**Issue by epicwhale** [ekino/EkinoNewRelicBundle#67]
When an exception is thrown in a Console Command, it doesn't seem be triggering the ExceptionListener onKernelException?

Does this bundle support logging of exceptions in console commands to new relic? As it doesn't seem to be working for me.

**Comment by mickadoo** [comment]
Should this work by default or do I need a different level of new relic subscription? I've tried throwing an exception from inside a console command but it doesn't get logged. However the same exception when thrown inside a controller action will show up in new relic.
