### ISSUE TITLE
Incorrect Console Event being used to set Input Options/Arguments as Custom Parameters

### ISSUE THREAD

**Issue by epicwhale** [ekino/EkinoNewRelicBundle#72]
The code which sets the New Relic Custom parameters when a symfony2 console command is executed is tapping into the onConsoleCommand event to do so.

At this stage --> https://github.com/ekino/EkinoNewRelicBundle/blob/master/Listener/CommandListener.php#L60 Symfony2 has not yet converted the console input into Options / Arguments, so in all circumstances, `$input->getOptions()` and `$input->getArguments()` will return an empty result and will never loop.

The correct event to tap into would be the Console Terminate event which takes places after the Command has been executed. Perhaps we can move this code logic into this separate event?

The bug was introduced in this commit https://github.com/ekino/EkinoNewRelicBundle/commit/403816a1e3d1be961b3899d6d6493675729c137b 

@gido Did you happen to face this issue or fix it in your local copy?

**Comment by Nyholm** [comment]
Im closing this since it is super old. Please make a comment if this still is an issue.
