### ISSUE TITLE
[feature] Monolog bridge for easy error reporting

### ISSUE THREAD

**Issue by inmarelibero** [ekino/EkinoNewRelicBundle#77]
I've just come across this article: [Using Monolog for PHP error reporting on New Relic](http://odino.org/using-monolog-for-php-error-reporting-on-new-relic/) and in my opinion providing a bridge between **Monolog** and **New Relic** could be useful.

Just to summarize, the service mentioned in the post:
- declares and uses a new `Monolog handler` (with fallback)
- uses internally the function `newrelic_notice_error()` for error reporting

NB: I should need to investigate more the "New Relics logs", but so far I understood that there's only the possibility to write some error messages, through the function `newrelic_notice_error()`

So, for example some features could be:
1. report an error directly in New Relic using nothing more than Monolog using a dedicated handler
2. provide a request listener for reporting an error to New Relic catching on every Symfony Exception
3. set an alert in New Relic (possible?) to catch this error

**Comment by moderndeveloperllc** [comment]
@inmarelibero That blog post is a bit out of date. Monolog now can connect to NewRelic directly: https://github.com/Seldaek/monolog/blob/master/doc/02-handlers-formatters-processors.md

**Comment by odino** [comment]
This is a pretty old issue! I'd recommend closing it -- esp. since nothing has moved so far. Probably it's too much effort for too less of a gain :)

**Comment by blackknight467** [comment]
so... i'm having trouble telling but what does this bundle do differently than just using the monolog handler?

also i assume you can add newrelic to monolog config as such?

```
monolog:
    handlers:
        newrelic:
            type: newrelic
            level: warning
```

**Comment by Nyholm** [comment]
I think that is an excellent idea. However, I would suggest to create it in a separate package.
