### ISSUE TITLE
Getting fatal error if newrelic extension is not loaded

### ISSUE THREAD

**Issue by igreiman** [ekino/EkinoNewRelicBundle#82]
If for some reason the newrelic extension is not loaded, using the bundle causes fatal errors and kills the process running it:

> Fatal error: Call to undefined function Ekino\Bundle\NewRelicBundle\NewRelic\newrelic_set_appname() in /someproject/vendor/ekino/newrelic-bundle/Ekino/Bundle/NewRelicBundle/NewRelic/NewRelicInteractor.php on line 21

The solution is to make sure the extension is loaded and also to make sure the function exists before calling it.

**Comment by rande** [comment]
There is a check when the container is being build: https://github.com/ekino/EkinoNewRelicBundle/blob/master/DependencyInjection/EkinoNewRelicExtension.php#L47-L49

**Comment by igreiman** [comment]
That check is irrelevant in case we're talking about a process that runs for a long period of time (a cron job for example), and in the middle of it newrelic goes away.
This is the situation I encountered, and therefore the solution I provided. 
Please reconsider this solution...

**Comment by aurelijusrozenas** [comment]
If someone stumbles here with same error: try manually clearing cache with `rm -rf app/cache/*`. Not sure what went wrong, but fixed the problem.

**Comment by rande** [comment]
The situation occurs when the cache is generated from a machine with newrelic and used on another with no newrelic

**Comment by aurelijusrozenas** [comment]
This happened after adding lib and configuration. Composer install went fine but clear cache failed with error message.

**Comment by igreiman** [comment]
Just to clarify - the problem I encounter had nothing to do with caching. It's a machine that was working fine until for some reason new relic was unavailable. That's when the fatal errors appeared and resulted in the termination of a long running process.
Also, it's not a one time occurrence, but it happens once in a while without any warnings.
Again - My fix will prevent EkinoNewRelicBundle from trying to use new relic's methods if it's not available at the time, without killing the parent process.

**Comment by rande** [comment]
@igreiman how newrelic extension became unavailable ?

**Comment by igreiman** [comment]
@rande - That's a good question which I'm afraid I have no answer to. 
Usually, by the time we see this issue, everything is already back to normal. My assumption is that we're talking about temporary connection issue that might be resulted from load or something similar. 
Again - because the script I'm running is a long running script (it's a worker that needs to run 24/7), every time this issue happens, it completely kills the script and I end up loosing at the very least an hour (usually it happens in the middle of the night and I find out about it only in the morning, a couple of hours after it happens... you know, Murphy's law...)

**Comment by igreiman** [comment]
@rande - Thanks for deciding to reopen this issue. In case you missed it - I already submitted a pull request with the fix. You might want to reopen that as well.

**Comment by rande** [comment]
@igreiman not sure it the correct way to fix the problem. I think we need to create a factory service which return the correct interactor instance.

**Comment by igreiman** [comment]
@rande - Yeah, that might be a more elegant solution, but it might suffer from the same problem as checking for the existence of new relic in the container instantiation, although to a lesser extent.

**Comment by rande** [comment]
@igreiman I don't see how the extension disappear without restarting the script, as the extension is loaded in memory.

**Comment by rande** [comment]
@igreiman if this really happening you might want notify the newrelic team about this

**Comment by igreiman** [comment]
@rande - Sure thing. Still would be nice if the bundle would not kill the job. Especially since reporting to new relic is just informative and should not have any effect on the script itself.

**Comment by nocive** [comment]
This is a problem for us too and it's not in a long running script.

During deployment flow, when we run doctrine migrations we get this error most of the time. Extension is loaded and properly configured but it doesn't really make any difference.

**Comment by Nicorr** [comment]
I'm having the same problem (errors at random times), how did you end up fixing it?

**Comment by jderusse** [comment]
@Nicorr are you sure, that the machine that build the cache is the same than the one which throws exception?

**Comment by Nyholm** [comment]
Any more updates here that could help debugging this issue?
Does this issue exist in 1.4.0?

**Comment by nocive** [comment]
@Nyholm we dropped newrelic entirely and never looked back. :no_mouth:

**Comment by Nyholm** [comment]
Im sorry to hear that. We are now working with a version 2.0 which will include something like #134 which will solve this issue. 

Im going to close this issue now. Thank you for getting back to me.
