### ISSUE TITLE
Make event listeners priority configurable

### ISSUE THREAD

**Issue by Nyholm** [ekino/EkinoNewRelicBundle#93]
It would be nice to be able configure what priority the event listeners have. Ie, I have a use case when I want have very high priority on the exception listener. 

The FOSRestBundle catches all exceptions and does not let our event listener to execute.

**Comment by mickadoo** [comment]
@Nyholm You can override service definitions to define whatever priority you want

**Comment by Nyholm** [comment]
Yes of course. But then I have to make sure to update my overridden service definitions every time I update the bundle.

**Comment by mickadoo** [comment]
I'm not sure I understand. Updating to a new version of the EkinoNewRelic bundle won't change the service definition. The only time you would need to change anything is if Ekino decided to change the service id of their listeners.

**Comment by Nyholm** [comment]
Yeah. Exactly.

**Comment by mickadoo** [comment]
It's pretty unlikely that Ekino will be changing their service id's

The exception listener ID hasn't changed since it was first introduced in [this commit](https://github.com/ekino/EkinoNewRelicBundle/commit/65c4114618d910e5f1c21175aee6577773000b31#diff-1c64574ff1f633f0df3aac6fa7a25c7b) over 2.5 years ago.

**Comment by Nyholm** [comment]
Please correct me if I'm wrong but if I wanted to change the priority of `ekino.new_relic.request_listener`'s `setTranscationName' event in my application I have to create a compiler pass and do something like... 
```php
$eventTags = $container->findDefinition('ekino.new_relic.request_listener')
    ->getTag('kernel.event_listener');
foreach ($eventTags as &$tag) {
    if ($tag['method'] === 'setTransactionName') {
        $tag['priority'] = -20;
    }
}
```

If Ekino chooses to change method name it will break my compiler pass without me noticing. The method name of `RequestListener::setTransactionName` is only used internally so it may change whenever someone feel that [I gave it a bad name](https://github.com/ekino/EkinoNewRelicBundle/commit/2124e7e4c76b0a252d947a42f735b2ba0c619594). Ie it's nothing I can trust. 

I wrote this ticket to see if there were any interest in having the priority of these event listeners configureable. I believe the standard [flow of the request](https://github.com/ekino/EkinoNewRelicBundle#flow-of-the-request) fits most of us but some might want to change it.

**Comment by mickadoo** [comment]
I'm no Symfony master, but I believe the event listeners priority is to change the priority that a single method in a named class is called for a certain event.

This is the definition for the Ekino request listener:

```
ekino.new_relic.request_listener:
    class: Ekino\Bundle\NewRelicBundle\Listener\RequestListener
    tags:
        - { name: kernel.event_listener, event: kernel.request, method: onCoreRequest, priority: 1 }
    arguments: ['@ekino.new_relic', '@ekino.new_relic.interactor', 
```

The `setTransactionName` method belongs to the interactor, not the listener class. It's not possible to change the order that the `onCoreRequest` does things. If you really want to you could of course extend from this class and override the onCoreRequest method to do things however you want.

**Comment by Nyholm** [comment]
Ah, I think you haven't seen the changes in master. I refactored the `RequestListener` quite a bit a couple of months back. Have a look at this file: https://github.com/ekino/EkinoNewRelicBundle/blob/master/Listener/RequestListener.php

**Comment by mickadoo** [comment]
Ah you're right - I was looking at the version we're using. But wouldn't it be possible to override the service definition in your own `services.yml` and also override the FOSRestBundle listener ids and setting all the priorities yourself?

**Comment by Nyholm** [comment]
Hm... Im hesitant that this is actually needed... If I do no t get back within a couple of weeks then we can consider closing this.

**Comment by mickadoo** [comment]
I forget why I got involved in this thread at all, so I don't feel I'm capable of giving useful input

**Comment by jderusse** [comment]
IMO being able to configure the priority of the listener is overkill and will add complexity to the configuration for a specific use case.

But, given this bundle is just reading the exception (and does not modify the flow) I'm fine to higher the priority to be executed first...

**Comment by Nyholm** [comment]
Closing due inactivity. 

#eu-fossa
